### PR TITLE
fix nix command to setup a dev env

### PR DESCRIPTION
**Pull request by fraidev**

### CODE REVIEW

**Comment by anmonteiro** [comment]
This is not needed anymore since we use `nix-filter`. If you're still seeing the error on master, can you let me know?

**Comment by anmonteiro** [comment]
Yeah the command is wrong but you shouldn't need `--impure`. Does this work?

```
nix develop -c $SHELL
```

**Comment by fraidev** [comment]
> 

Oh ok, using `nix develop -c $SHELL`, I have:

```
▷ nix develop -c $SHELL                                                                                                                                              ✔ add-ocaml-lsp
error: the path '~/.gitconfig' can not be resolved in pure mode
(use '--show-trace' to show detailed location information)

~/workspace/piaf
▷ nix develop --show-trace -c $SHELL                                                                                                                                 ✔ add-ocaml-lsp
error: the path '~/.gitconfig' can not be resolved in pure mode

       … while evaluating 'filter'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/sources.nix:106:22:

          105|       inherit (orig) origSrc;
          106|       filter = path: type: filter path type && orig.filter path type;
             |                      ^
          107|       name = if name != null then name else orig.name;

       … from call site

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/sources.nix:261:17:

          260|       inherit origSrc filter name;
          261|       outPath = builtins.path { inherit filter name; path = origSrc; };
             |                 ^
          262|     };

       … while adding path '/nix/store/fzs6gy2r4wd3ph5jcvjhngw0dy8clq1f-source'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/sources.nix:261:17:

          260|       inherit origSrc filter name;
          261|       outPath = builtins.path { inherit filter name; path = origSrc; };
             |                 ^
          262|     };

       … while evaluating the attribute 'src' of the derivation 'carl'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

       … while evaluating anonymous lambda

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/lists.nix:662:30:

          661|   */
          662|   subtractLists = e: filter (x: !(elem x e));
             |                              ^
          663|

       … from call site

       … while evaluating 'mergeInputs'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/build-support/mkshell/default.nix:17:17:

           16| let
           17|   mergeInputs = name:
             |                 ^
           18|     (attrs.${name} or [ ]) ++

       … from call site

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/build-support/mkshell/default.nix:37:36:

           36|   buildInputs = mergeInputs "buildInputs";
           37|   nativeBuildInputs = packages ++ (mergeInputs "nativeBuildInputs");
             |                                    ^
           38|   propagatedBuildInputs = mergeInputs "propagatedBuildInputs";

       … while evaluating 'imap1'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/lists.nix:117:14:

          116|   */
          117|   imap1 = f: list: genList (n: f (n + 1) (elemAt list n)) (length list);
             |              ^
          118|

       … from call site

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/trivial.nix:138:19:

          137|   */
          138|   flip = f: a: b: f b a;
             |                   ^
          139|

       … while evaluating 'flip'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/trivial.nix:138:16:

          137|   */
          138|   flip = f: a: b: f b a;
             |                ^
          139|

       … from call site

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/stdenv/generic/make-derivation.nix:192:49:

          191|   checkDependencyList = checkDependencyList' [];
          192|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
             |                                                 ^
          193|     if lib.isDerivation dep || isNull dep || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep

       … while evaluating 'checkDependencyList''

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/stdenv/generic/make-derivation.nix:192:43:

          191|   checkDependencyList = checkDependencyList' [];
          192|   checkDependencyList' = positions: name: deps: lib.flip lib.imap1 deps (index: dep:
             |                                           ^
          193|     if lib.isDerivation dep || isNull dep || builtins.typeOf dep == "string" || builtins.typeOf dep == "path" then dep

       … from call site

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/stdenv/generic/make-derivation.nix:212:41:

          211|       (map (drv: drv.__spliced.buildBuild or drv) (checkDependencyList "depsBuildBuild" depsBuildBuild))
          212|       (map (drv: drv.nativeDrv or drv) (checkDependencyList "nativeBuildInputs" nativeBuildInputs
             |                                         ^
          213|          ++ lib.optional separateDebugInfo' ../../build-support/setup-hooks/separate-debug-info.sh

       … while evaluating 'chooseDevOutputs'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/lib/attrsets.nix:609:22:

          608|   /* Pick the outputs of packages to place in buildInputs */
          609|   chooseDevOutputs = drvs: builtins.map getDev drvs;
             |                      ^
          610|

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/stdenv/generic/make-derivation.nix:253:32:

          252|   computedImpureHostDeps =
          253|     lib.unique (lib.concatMap (input: input.__propagatedImpureHostDeps or [])
             |                                ^
          254|       (stdenv.extraNativeBuildInputs

       … from call site

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/stdenv/generic/make-derivation.nix:253:17:

          252|   computedImpureHostDeps =
          253|     lib.unique (lib.concatMap (input: input.__propagatedImpureHostDeps or [])
             |                 ^
          254|       (stdenv.extraNativeBuildInputs

       … while evaluating the attribute '__impureHostDeps' of the derivation 'nix-shell'

       at /nix/store/xqsj5ndimfaw6k09nflzd4qbwshkld4j-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

```

**Comment by fraidev** [comment]
> Fixed in [df7a5b1](https://github.com/anmonteiro/piaf/commit/df7a5b151664a2cec79ac0340ca7bff51a35d223). try rebasing

Oh, it's working now with `nix develop -c $SHELL`. 
I edited the commit.

**Comment by anmonteiro** [comment]
Nice, thanks.

**Pull request merged**
