### PR TITLE
"Unvendor" multipart_form, change name to `piaf_multipart_form`

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by dinosaure** [comment]
Hi, I see this PR but the code did not mention the copyright needed by the MIT license at least, Could you add it into the directory or prepend files with such copyright?

**Comment by anmonteiro** [comment]
Ooooops, sorry about that @dinosaure. Will do!

**Comment by anmonteiro** [comment]
@dinosaure commit ed5c9d3 adds the original license text and a mention in the README. Does that seem adequate to you?

**Comment by dinosaure** [comment]
Thanks! 👍

**Pull request merged**
