### PR TITLE
More cert tests

### PR DESCRIPTION
**Pull request by Firgeis**
This PR contains:

* New certificates with longer expiration (10 yrs) for testing
* Helper server accepts certs override as a parameters
* New test that verifies a certificate with a RSA key and the correct DNS name in a SAN

### CODE REVIEW

**Comment by anmonteiro** [comment]
This should be good to go after running `dune build @fmt --auto-promote`.

**Review by anmonteiro — APPROVED** [review]

**Comment by Firgeis** [comment]
@anmonteiro Formatting done :)

**Comment by anmonteiro** [comment]
Hey @Firgeis, tests are now failing with: 
```
EXN: SSL accept() error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
```

**Comment by Firgeis** [comment]
> Hey @Firgeis, tests are now failing with:
> 
> ```
> EXN: SSL accept() error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
> ```

I'm running `dune test` and they don't fail at least locally. Are the CI tests running them differently so I can check?

**Comment by anmonteiro** [comment]
I'm running this locally with OpenSSL 1.1.1k and I get the same failures.

**Comment by anmonteiro** [comment]
Full log:

```
test_client.exe: [DEBUG] TCP_NODELAY set
piaf.client: [DEBUG] Trying connection to localhost (127.0.0.1:9443)
piaf.client: [INFO] Connected to localhost (127.0.0.1:9443)
piaf.openssl: [INFO] ALPN: offering http/1.1
piaf.openssl: [INFO] ALPN: offering http/1.0
piaf.openssl: [ERROR] SSL Error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
piaf.openssl: [ERROR] self signed certificate (18)
piaf.client: [INFO] Closing connection to localhost (127.0.0.1:9443)
EXN: SSL accept() error: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
[invalid] result is Error _

```

**Comment by anmonteiro** [comment]
Thanks!

**Pull request merged**
